name: CI - Build and Test

on:
  push:
    branches:
      - main
      - '**/feature/**'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # Match the TargetFramework used in your project (net9.0)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: dotnet restore

      # Step 4: Build the solution
      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      # Step 5: Run tests
      - name: Run tests
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"